import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { HARNESSES, SECTION_END, SECTION_START, demoteHeadings, harnessById, renderInstall, renderRefresh, upsertSection, GENERATED } from './skills';

const body = readFileSync(new URL('../../agent/skill.md', import.meta.url), 'utf8');

describe('agent skill rendering', () => {
  it('gives Claude Code a skill with name and description frontmatter', () => {
    const out = harnessById('claude-project')!.render(body);
    expect(out.startsWith('---\nname: vs-canvas\ndescription: "Use the VS Canvas MCP tools')).toBe(true);
    expect(out).toContain('# VS Canvas');
  });

  it('uses each harness native frontmatter', () => {
    expect(harnessById('copilot')!.render(body)).toMatch(/^---\napplyTo: "\*\*"\ndescription: /);
    expect(harnessById('cursor')!.render(body)).toMatch(/alwaysApply: false\n---/);
    expect(harnessById('windsurf')!.render(body)).toMatch(/^---\ntrigger: model_decision\n/);
    expect(harnessById('cline')!.render(body).startsWith('<!-- Generated by VS Canvas')).toBe(true);
  });

  it('every harness has a unique target and renders the whole guide', () => {
    const targets = HARNESSES.map((h) => `${h.scope}:${h.path}`);
    expect(new Set(targets).size).toBe(targets.length);
    for (const h of HARNESSES) expect(h.render(body)).toContain('Fix what the linter reports');
  });

  it('demotes headings outside code fences only', () => {
    expect(demoteHeadings('# A\n## B\n```\n# not a heading\n```\ntext')).toBe('## A\n### B\n```\n# not a heading\n```\ntext');
  });
});

describe('shared-file sections', () => {
  const section = harnessById('agents-md')!.render(body);

  it('appends to an existing file without touching its content', () => {
    const out = upsertSection('# Project rules\n\nUse pnpm.\n', section)!;
    expect(out.startsWith('# Project rules\n\nUse pnpm.\n\n' + SECTION_START)).toBe(true);
    expect(out.trimEnd().endsWith(SECTION_END)).toBe(true);
    expect(out).toContain('## VS Canvas');
  });

  it('replaces only our section on reinstall and is idempotent', () => {
    const first = upsertSection('# Rules\n', `${SECTION_START}\nold\n${SECTION_END}\n\n## Later\nkeep me\n`)!;
    const withNew = upsertSection(first, section)!;
    expect(withNew).toContain('keep me');
    expect(withNew).not.toContain('\nold\n');
    expect(upsertSection(withNew, section)).toBeUndefined();
  });

  it('reports no change when an owned file is already current', () => {
    const h = harnessById('cursor')!;
    expect(renderInstall(h, body, h.render(body))).toBeUndefined();
    expect(renderInstall(h, body, 'stale')).toBe(h.render(body));
  });
});

describe('renderRefresh', () => {
  const file = harnessById('cursor')!;
  const sect = harnessById('agents-md')!;

  it('leaves missing and unmanaged files alone', () => {
    expect(renderRefresh(file, body, undefined)).toBeUndefined();
    expect(renderRefresh(sect, body, undefined)).toBeUndefined();
    expect(renderRefresh(file, body, 'my own rules\n')).toBeUndefined();
    expect(renderRefresh(sect, body, '# My AGENTS.md\n')).toBeUndefined();
  });

  it('updates a managed whole file and a managed section', () => {
    expect(renderRefresh(file, body, `${GENERATED}\nold canvas_play_flow`)).toBe(file.render(body));
    const stale = `# Rules\n\n${SECTION_START}\nold\n${SECTION_END}\n\n## Later\nkeep\n`;
    const out = renderRefresh(sect, body, stale)!;
    expect(out).toContain('## Later\nkeep');
    expect(out).not.toContain('\nold\n');
    expect(out).toContain(SECTION_START);
  });

  it('reports no change when already current', () => {
    expect(renderRefresh(file, body, file.render(body))).toBeUndefined();
    expect(renderRefresh(sect, body, sect.render(body))).toBeUndefined();
  });
});
