import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import {
  GENERATED, HARNESSES, SECTION_END, SECTION_START, demoteHeadings, harnessById, installedVersion, refreshAll, renderInstall,
  renderRefresh, upsertSection,
} from './skills';

const body = readFileSync(new URL('../../agent/skill.md', import.meta.url), 'utf8');
const V = '0.3.0';

describe('agent skill rendering', () => {
  it('gives Claude Code a skill with name and description frontmatter', () => {
    const out = harnessById('claude-project')!.render(body, V);
    expect(out.startsWith('---\nname: vs-canvas\ndescription: "Use the VS Canvas MCP tools')).toBe(true);
    expect(out).toContain('# VS Canvas');
  });

  it('uses each harness native frontmatter', () => {
    expect(harnessById('copilot')!.render(body, V)).toMatch(/^---\napplyTo: "\*\*"\ndescription: /);
    expect(harnessById('cursor')!.render(body, V)).toMatch(/alwaysApply: false\n---/);
    expect(harnessById('windsurf')!.render(body, V)).toMatch(/^---\ntrigger: model_decision\n/);
    expect(harnessById('cline')!.render(body, V).startsWith('<!-- Generated by VS Canvas')).toBe(true);
  });

  it('every harness has a unique target and renders the whole guide', () => {
    const targets = HARNESSES.map((h) => `${h.scope}:${h.path}`);
    expect(new Set(targets).size).toBe(targets.length);
    for (const h of HARNESSES) expect(h.render(body, V)).toContain('Fix what the linter reports');
  });

  it('demotes headings outside code fences only', () => {
    expect(demoteHeadings('# A\n## B\n```\n# not a heading\n```\ntext')).toBe('## A\n### B\n```\n# not a heading\n```\ntext');
  });
});

describe('shared-file sections', () => {
  const section = harnessById('agents-md')!.render(body, V);

  it('appends to an existing file without touching its content', () => {
    const out = upsertSection('# Project rules\n\nUse pnpm.\n', section)!;
    expect(out.startsWith('# Project rules\n\nUse pnpm.\n\n' + SECTION_START)).toBe(true);
    expect(out.trimEnd().endsWith(SECTION_END)).toBe(true);
    expect(out).toContain('## VS Canvas');
  });

  it('replaces only our section on reinstall and is idempotent', () => {
    const first = upsertSection('# Rules\n', `${SECTION_START}\nold\n${SECTION_END}\n\n## Later\nkeep me\n`)!;
    const withNew = upsertSection(first, section)!;
    expect(withNew).toContain('keep me');
    expect(withNew).not.toContain('\nold\n');
    expect(upsertSection(withNew, section)).toBeUndefined();
  });

  it('reports no change when an owned file is already current', () => {
    const h = harnessById('cursor')!;
    expect(renderInstall(h, body, V, h.render(body, V))).toBeUndefined();
    expect(renderInstall(h, body, V, 'stale')).toBe(h.render(body, V));
  });
});

describe('installedVersion', () => {
  it('reads the stamp, treats the old marker as 0.0.0 and returns undefined without a marker', () => {
    expect(installedVersion(`${GENERATED('1.2.3')}\nbody`)).toBe('1.2.3');
    expect(installedVersion(`${GENERATED('1.2.3-beta.1')}\nbody`)).toBe('1.2.3-beta.1');
    expect(installedVersion('<!-- Generated by VS Canvas. Run "VS Canvas: Install Agent Skills" to update. -->')).toBe('0.0.0');
    expect(installedVersion('my own rules')).toBeUndefined();
  });

  it('looks inside the marked block for shared files', () => {
    const text = `${GENERATED('9.9.9')}\n${SECTION_START}\n${GENERATED('0.2.0')}\nx\n${SECTION_END}\n`;
    expect(installedVersion(text)).toBe('0.2.0');
    expect(installedVersion(`# mine\n${SECTION_START}\nno marker\n${SECTION_END}`)).toBeUndefined();
  });
});

describe('renderRefresh', () => {
  const file = harnessById('cursor')!;
  const sect = harnessById('agents-md')!;
  const at = (v: string) => file.render(body, v);

  it('leaves missing and unmanaged files alone', () => {
    expect(renderRefresh(file, body, V, undefined)).toBeUndefined();
    expect(renderRefresh(sect, body, V, undefined)).toBeUndefined();
    expect(renderRefresh(file, body, V, 'my own rules\n')).toBeUndefined();
    expect(renderRefresh(sect, body, V, '# My AGENTS.md\n')).toBeUndefined();
  });

  it('upgrades an older stamp and writes the new one', () => {
    const out = renderRefresh(file, body, V, `${GENERATED('0.2.9')}\nold canvas_play_flow`);
    expect(out).toBe(at(V));
    expect(out).toContain('Generated by VS Canvas 0.3.0.');
  });

  it('upgrades an unstamped legacy marker', () => {
    const legacy = '<!-- Generated by VS Canvas. Run "VS Canvas: Install Agent Skills" to update. -->\nold';
    expect(renderRefresh(file, body, V, legacy)).toBe(at(V));
  });

  it('compares numerically, ignoring prerelease suffixes', () => {
    expect(renderRefresh(file, body, '0.10.0', at('0.9.0'))).toBe(at('0.10.0'));
    expect(renderRefresh(file, body, '1.0.0', at('0.99.99-beta.2'))).toBe(at('1.0.0'));
    expect(renderRefresh(file, body, '0.3.0', at('0.3.0-beta.1'))).toBeUndefined();
  });

  it('does not write for the same version, even when content differs', () => {
    expect(renderRefresh(file, body, V, at(V))).toBeUndefined();
    expect(renderRefresh(file, body, V, `${GENERATED(V)}\nteammate edit`)).toBeUndefined();
  });

  it('does not downgrade', () => {
    expect(renderRefresh(file, body, V, at('0.4.0'))).toBeUndefined();
    expect(renderRefresh(sect, body, V, sect.render(body, '1.0.0'))).toBeUndefined();
  });

  it('upgrades a section and preserves the surrounding user content', () => {
    const stale = `# Rules\n\n${SECTION_START}\n${GENERATED('0.1.0')}\nold\n${SECTION_END}\n\n## Later\nkeep\n`;
    const out = renderRefresh(sect, body, V, stale)!;
    expect(out.startsWith('# Rules\n\n' + SECTION_START)).toBe(true);
    expect(out).toContain('## Later\nkeep');
    expect(out).not.toContain('\nold\n');
    expect(installedVersion(out)).toBe(V);
  });
});

describe('refreshAll', () => {
  const stale = (h: (typeof HARNESSES)[number]) => h.render(body, '0.1.0');

  it('writes what is stale and reports a failing write without stopping the rest', async () => {
    const files = new Map<string, string>();
    for (const h of HARNESSES) files.set(`/${h.scope}/${h.path}`, stale(h));
    const written: string[] = [];
    const bad = '/workspace/' + harnessById('cursor')!.path;
    const res = await refreshAll(body, V, {
      root: (h) => `/${h.scope}`,
      read: async (p) => files.get(p),
      write: async (p, t) => {
        if (p === bad) throw new Error('read-only');
        written.push(p);
        files.set(p, t);
      },
    });
    expect(res.failed).toEqual([{ path: bad, error: 'read-only' }]);
    expect(res.updated).toHaveLength(HARNESSES.length - 1);
    expect(written).toEqual(res.updated);
    expect(files.get('/workspace/AGENTS.md')).toContain(`VS Canvas ${V}.`);
  });

  it('survives read errors and missing roots, and is a no-op when current', async () => {
    const res = await refreshAll(body, V, {
      root: (h) => (h.scope === 'user' ? undefined : '/r'),
      read: async (p) => {
        if (p.endsWith('AGENTS.md')) throw new Error('boom');
        return p.includes('.clinerules') ? harnessById('cline')!.render(body, V) : undefined;
      },
      write: async () => { throw new Error('should not write'); },
    });
    expect(res.updated).toEqual([]);
    expect(res.failed).toHaveLength(1);
    expect(res.failed[0].error).toBe('boom');
  });
});
