// Agent skill files: one canonical guide (agent/skill.md) rendered in each agent harness's native format.
// Pure (no vscode import) so rendering and merging are unit-tested.

export type HarnessId =
  | 'claude-project'
  | 'claude-user'
  | 'copilot'
  | 'cursor'
  | 'windsurf'
  | 'cline'
  | 'agents-md'
  | 'gemini';

export type Harness = {
  id: HarnessId;
  label: string;
  detail: string;
  /** 'workspace' paths are relative to the first workspace folder; 'user' paths to the home directory. */
  scope: 'workspace' | 'user';
  path: string;
  /** 'file' = a file we own (overwritten); 'section' = a marked section inside a shared file (upserted). */
  mode: 'file' | 'section';
  /** Paths (same scope) whose presence suggests the harness is in use, so the installer preselects it. */
  detect: string[];
  render: (body: string) => string;
};

export const SKILL_NAME = 'vs-canvas';

/** One line used by harnesses that decide from a description whether to load the guide. */
export const SKILL_DESCRIPTION =
  'Use the VS Canvas MCP tools (canvas_*, code_*) to put code on an infinite canvas in VS Code: explain flows ' +
  'across files, trace bugs with evidence, map an unfamiliar repo, and draw C4, UML, flowchart and ERD diagrams. ' +
  'Use when explaining how code works across several files, investigating a bug, orienting in a repo, or when the ' +
  'user asks for a diagram, map or canvas.';

export const GENERATED = '<!-- Generated by VS Canvas. Run "VS Canvas: Install Agent Skills" to update. -->';
export const SECTION_START = '<!-- vs-canvas:start -->';
export const SECTION_END = '<!-- vs-canvas:end -->';

const frontmatter = (fields: Record<string, string>) =>
  '---\n' + Object.entries(fields).map(([k, v]) => `${k}: ${v}`).join('\n') + '\n---\n\n';

const quote = (s: string) => JSON.stringify(s);

/** Push every markdown heading down one level (the guide becomes a `##` section inside AGENTS.md etc.). */
export function demoteHeadings(md: string): string {
  let fence = false;
  return md
    .split('\n')
    .map((line) => {
      if (/^\s*```/.test(line)) fence = !fence;
      return !fence && /^#{1,5} /.test(line) ? '#' + line : line;
    })
    .join('\n');
}

const asFile = (head: string, body: string) => head + GENERATED + '\n\n' + body.trim() + '\n';
const asSection = (body: string) => `${SECTION_START}\n${GENERATED}\n\n${demoteHeadings(body.trim())}\n${SECTION_END}\n`;

const claude = (body: string) => asFile(frontmatter({ name: SKILL_NAME, description: quote(SKILL_DESCRIPTION) }), body);

export const HARNESSES: Harness[] = [
  {
    id: 'claude-project', label: 'Claude Code (this project)', detail: '.claude/skills/vs-canvas/SKILL.md',
    scope: 'workspace', path: '.claude/skills/vs-canvas/SKILL.md', mode: 'file', detect: ['.claude', 'CLAUDE.md', '.mcp.json'],
    render: claude,
  },
  {
    id: 'claude-user', label: 'Claude Code (all projects)', detail: '~/.claude/skills/vs-canvas/SKILL.md',
    scope: 'user', path: '.claude/skills/vs-canvas/SKILL.md', mode: 'file', detect: [],
    render: claude,
  },
  {
    id: 'copilot', label: 'GitHub Copilot (VS Code)', detail: '.github/instructions/vs-canvas.instructions.md',
    scope: 'workspace', path: '.github/instructions/vs-canvas.instructions.md', mode: 'file',
    detect: ['.github/copilot-instructions.md', '.github/instructions'],
    render: (body) => asFile(frontmatter({ applyTo: quote('**'), description: quote(SKILL_DESCRIPTION) }), body),
  },
  {
    id: 'cursor', label: 'Cursor', detail: '.cursor/rules/vs-canvas.mdc',
    scope: 'workspace', path: '.cursor/rules/vs-canvas.mdc', mode: 'file', detect: ['.cursor', '.cursorrules'],
    render: (body) => asFile(frontmatter({ description: quote(SKILL_DESCRIPTION), globs: '', alwaysApply: 'false' }), body),
  },
  {
    id: 'windsurf', label: 'Windsurf', detail: '.windsurf/rules/vs-canvas.md',
    scope: 'workspace', path: '.windsurf/rules/vs-canvas.md', mode: 'file', detect: ['.windsurf', '.windsurfrules'],
    render: (body) => asFile(frontmatter({ trigger: 'model_decision', description: quote(SKILL_DESCRIPTION) }), body),
  },
  {
    id: 'cline', label: 'Cline', detail: '.clinerules/vs-canvas.md',
    scope: 'workspace', path: '.clinerules/vs-canvas.md', mode: 'file', detect: ['.clinerules'],
    render: (body) => asFile('', body),
  },
  {
    id: 'agents-md', label: 'AGENTS.md (Codex, Copilot, Amp and others)', detail: 'section in AGENTS.md',
    scope: 'workspace', path: 'AGENTS.md', mode: 'section', detect: ['AGENTS.md'],
    render: asSection,
  },
  {
    id: 'gemini', label: 'Gemini CLI', detail: 'section in GEMINI.md',
    scope: 'workspace', path: 'GEMINI.md', mode: 'section', detect: ['GEMINI.md', '.gemini'],
    render: asSection,
  },
];

export const harnessById = (id: string) => HARNESSES.find((h) => h.id === id);

/**
 * Insert or replace our marked section in a shared file, leaving everything else untouched. Returns the new text,
 * or undefined when it is already current.
 */
export function upsertSection(existing: string | undefined, section: string): string | undefined {
  const text = existing ?? '';
  const start = text.indexOf(SECTION_START);
  const end = text.indexOf(SECTION_END, start + 1);
  let next: string;
  if (start !== -1 && end !== -1) {
    const after = text.slice(end + SECTION_END.length).replace(/^\r?\n/, '');
    next = text.slice(0, start) + section + after;
  } else {
    next = text.trim() ? text.replace(/\s*$/, '\n\n') + section : section;
  }
  return next === text ? undefined : next;
}

/** New content for a harness file given what is on disk (undefined = nothing to write). */
export function renderInstall(h: Harness, body: string, existing: string | undefined): string | undefined {
  const content = h.render(body);
  if (h.mode === 'section') return upsertSection(existing, content);
  return existing === content ? undefined : content;
}

/**
 * New content for an already-installed guide, or undefined (nothing to write). Only files that VS Canvas manages are
 * refreshed: a missing file is never created, and a file without our marker is never touched.
 */
export function renderRefresh(h: Harness, body: string, existing: string | undefined): string | undefined {
  if (existing === undefined) return undefined;
  const managed = h.mode === 'section' ? existing.includes(SECTION_START) : existing.includes(GENERATED);
  return managed ? renderInstall(h, body, existing) : undefined;
}
