// Agent skill files: one canonical guide (agent/skill.md) rendered in each agent harness's native format.
// Pure (no vscode import) so rendering and merging are unit-tested.

import * as path from 'node:path';

export type HarnessId =
  | 'claude-project'
  | 'claude-user'
  | 'copilot'
  | 'cursor'
  | 'windsurf'
  | 'cline'
  | 'agents-md'
  | 'gemini';

export type Harness = {
  id: HarnessId;
  label: string;
  detail: string;
  /** 'workspace' paths are relative to the first workspace folder; 'user' paths to the home directory. */
  scope: 'workspace' | 'user';
  path: string;
  /** 'file' = a file we own (overwritten); 'section' = a marked section inside a shared file (upserted). */
  mode: 'file' | 'section';
  /** Paths (same scope) whose presence suggests the harness is in use, so the installer preselects it. */
  detect: string[];
  render: (body: string, version: string) => string;
};

export const SKILL_NAME = 'vs-canvas';

/** One line used by harnesses that decide from a description whether to load the guide. */
export const SKILL_DESCRIPTION =
  'Use the VS Canvas MCP tools (canvas_*, code_*) to put code on an infinite canvas in VS Code: explain flows ' +
  'across files, trace bugs with evidence, map an unfamiliar repo, and draw C4, UML, flowchart and ERD diagrams. ' +
  'Use when explaining how code works across several files, investigating a bug, orienting in a repo, or when the ' +
  'user asks for a diagram, map or canvas.';

/** Marker stamped into every generated file; carries the extension version that wrote it. */
export const GENERATED = (version: string) =>
  `<!-- Generated by VS Canvas ${version}. Run "VS Canvas: Install Agent Skills" to update. -->`;
export const SECTION_START = '<!-- vs-canvas:start -->';
export const SECTION_END = '<!-- vs-canvas:end -->';

const frontmatter = (fields: Record<string, string>) =>
  '---\n' + Object.entries(fields).map(([k, v]) => `${k}: ${v}`).join('\n') + '\n---\n\n';

const quote = (s: string) => JSON.stringify(s);

/** Push every markdown heading down one level (the guide becomes a `##` section inside AGENTS.md etc.). */
export function demoteHeadings(md: string): string {
  let fence = false;
  return md
    .split('\n')
    .map((line) => {
      if (/^\s*```/.test(line)) fence = !fence;
      return !fence && /^#{1,5} /.test(line) ? '#' + line : line;
    })
    .join('\n');
}

const asFile = (head: string, body: string, version: string) => head + GENERATED(version) + '\n\n' + body.trim() + '\n';
const asSection = (body: string, version: string) =>
  `${SECTION_START}\n${GENERATED(version)}\n\n${demoteHeadings(body.trim())}\n${SECTION_END}\n`;

const claude = (body: string, version: string) =>
  asFile(frontmatter({ name: SKILL_NAME, description: quote(SKILL_DESCRIPTION) }), body, version);

export const HARNESSES: Harness[] = [
  {
    id: 'claude-project', label: 'Claude Code (this project)', detail: '.claude/skills/vs-canvas/SKILL.md',
    scope: 'workspace', path: '.claude/skills/vs-canvas/SKILL.md', mode: 'file', detect: ['.claude', 'CLAUDE.md', '.mcp.json'],
    render: claude,
  },
  {
    id: 'claude-user', label: 'Claude Code (all projects)', detail: '~/.claude/skills/vs-canvas/SKILL.md',
    scope: 'user', path: '.claude/skills/vs-canvas/SKILL.md', mode: 'file', detect: [],
    render: claude,
  },
  {
    id: 'copilot', label: 'GitHub Copilot (VS Code)', detail: '.github/instructions/vs-canvas.instructions.md',
    scope: 'workspace', path: '.github/instructions/vs-canvas.instructions.md', mode: 'file',
    detect: ['.github/copilot-instructions.md', '.github/instructions'],
    render: (body, v) => asFile(frontmatter({ applyTo: quote('**'), description: quote(SKILL_DESCRIPTION) }), body, v),
  },
  {
    id: 'cursor', label: 'Cursor', detail: '.cursor/rules/vs-canvas.mdc',
    scope: 'workspace', path: '.cursor/rules/vs-canvas.mdc', mode: 'file', detect: ['.cursor', '.cursorrules'],
    render: (body, v) => asFile(frontmatter({ description: quote(SKILL_DESCRIPTION), globs: '', alwaysApply: 'false' }), body, v),
  },
  {
    id: 'windsurf', label: 'Windsurf', detail: '.windsurf/rules/vs-canvas.md',
    scope: 'workspace', path: '.windsurf/rules/vs-canvas.md', mode: 'file', detect: ['.windsurf', '.windsurfrules'],
    render: (body, v) => asFile(frontmatter({ trigger: 'model_decision', description: quote(SKILL_DESCRIPTION) }), body, v),
  },
  {
    id: 'cline', label: 'Cline', detail: '.clinerules/vs-canvas.md',
    scope: 'workspace', path: '.clinerules/vs-canvas.md', mode: 'file', detect: ['.clinerules'],
    render: (body, v) => asFile('', body, v),
  },
  {
    id: 'agents-md', label: 'AGENTS.md (Codex, Copilot, Amp and others)', detail: 'section in AGENTS.md',
    scope: 'workspace', path: 'AGENTS.md', mode: 'section', detect: ['AGENTS.md'],
    render: asSection,
  },
  {
    id: 'gemini', label: 'Gemini CLI', detail: 'section in GEMINI.md',
    scope: 'workspace', path: 'GEMINI.md', mode: 'section', detect: ['GEMINI.md', '.gemini'],
    render: asSection,
  },
];

export const harnessById = (id: string) => HARNESSES.find((h) => h.id === id);

/**
 * Insert or replace our marked section in a shared file, leaving everything else untouched. Returns the new text,
 * or undefined when it is already current.
 */
export function upsertSection(existing: string | undefined, section: string): string | undefined {
  const text = existing ?? '';
  const start = text.indexOf(SECTION_START);
  const end = text.indexOf(SECTION_END, start + 1);
  let next: string;
  if (start !== -1 && end !== -1) {
    const after = text.slice(end + SECTION_END.length).replace(/^\r?\n/, '');
    next = text.slice(0, start) + section + after;
  } else {
    next = text.trim() ? text.replace(/\s*$/, '\n\n') + section : section;
  }
  return next === text ? undefined : next;
}

/** New content for a harness file given what is on disk (undefined = nothing to write). */
export function renderInstall(h: Harness, body: string, version: string, existing: string | undefined): string | undefined {
  const content = h.render(body, version);
  if (h.mode === 'section') return upsertSection(existing, content);
  return existing === content ? undefined : content;
}

const MARKER = /<!-- Generated by VS Canvas(?: (\S+?))?\. Run "VS Canvas: Install Agent Skills"/;

/**
 * The version stamped in a generated file (inside our marked block for shared files): the version string,
 * '0.0.0' for an older unstamped marker, undefined when there is no marker (not managed by VS Canvas).
 */
export function installedVersion(text: string): string | undefined {
  const start = text.indexOf(SECTION_START);
  const end = start === -1 ? -1 : text.indexOf(SECTION_END, start + 1);
  const scope = start !== -1 && end !== -1 ? text.slice(start, end) : text;
  const m = MARKER.exec(scope);
  return m ? (m[1] ?? '0.0.0') : undefined;
}

/** major.minor.patch as numbers (prerelease and build suffixes ignored); undefined when it does not parse. */
function semver(v: string): [number, number, number] | undefined {
  const m = /^v?(\d+)\.(\d+)\.(\d+)/.exec(v);
  return m ? [Number(m[1]), Number(m[2]), Number(m[3])] : undefined;
}

/** True when `a` is strictly older than `b`. An unparseable `a` counts as oldest, an unparseable `b` as unknown. */
function isOlder(a: string, b: string): boolean {
  const y = semver(b);
  if (!y) return false;
  const x = semver(a) ?? [0, 0, 0];
  for (let i = 0; i < 3; i++) if (x[i] !== y[i]) return x[i] < y[i];
  return false;
}

/**
 * New content for an already-installed guide, or undefined (nothing to write). Only files VS Canvas manages are
 * refreshed, and only when the version they were written by is older than the running one: a missing file is never
 * created, a file without our marker is never touched, and the same or a newer version is left alone (so teammates on
 * different versions do not fight over a committed file).
 */
export function renderRefresh(h: Harness, body: string, version: string, existing: string | undefined): string | undefined {
  if (existing === undefined) return undefined;
  const installed = installedVersion(existing);
  if (installed === undefined || !isOlder(installed, version)) return undefined;
  return renderInstall(h, body, version, existing);
}

export type RefreshIO = {
  /** Directory the harness path is relative to, or undefined when unavailable (e.g. no workspace folder). */
  root: (h: Harness) => string | undefined;
  read: (path: string) => Promise<string | undefined>;
  write: (path: string, text: string) => Promise<void>;
};

/** Refresh every installed harness file. Never throws: failures are reported per file and the rest still run. */
export async function refreshAll(
  body: string,
  version: string,
  io: RefreshIO,
): Promise<{ updated: string[]; failed: { path: string; error: string }[] }> {
  const updated: string[] = [];
  const failed: { path: string; error: string }[] = [];
  for (const h of HARNESSES) {
    let file = h.path;
    try {
      const root = io.root(h);
      if (!root) continue;
      file = path.join(root, ...h.path.split('/'));
      const next = renderRefresh(h, body, version, await io.read(file));
      if (next === undefined) continue;
      await io.write(file, next);
      updated.push(file);
    } catch (e) {
      failed.push({ path: file, error: e instanceof Error ? e.message : String(e) });
    }
  }
  return { updated, failed };
}
